os: linux
sudo: required
language: nodejs
node_js:
  - "8"
branches:
  only:
    - master
stages:
  - name: softdoor
  - name: test

jobs:
  include:
    - stage: test
      name: "test-1"
      env:
        - GITHUB=https://github.com/SystemLight/softdoor
      script:
        - echo i am test-1

    - stage: test
      name: "test-2"
      env:
        - GITHUB=https://github.com/SystemLight/softdoor
      script:
        - echo i am test-2

    - stage: softdoor
      name: "softdoor-1"
      env:
        - GITHUB=https://github.com/SystemLight/madtornado
      before_install:
        - echo before_install
      install:
        - npm install -i
      before_script:
        - echo before_script
      script:
        - echo script
      after_success:
        - echo $TRAVIS_TEST_RESULT
      after_failure:
        - echo $TRAVIS_TEST_RESULT
      before_deploy:
        - echo $TRAVIS_TAG
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tag: true
          branch: master
        tag: latest
        condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'
#          all_branches: true
      after_script:
        - echo after_script
