language: node_js
node_js:
  - '8'
before_deploy: npm run build
deploy:
  provider: npm
  email: 1466335092@qq.com
  skip_cleanup: true
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: true
    branch: master
  tag: latest
