os: linux
sudo: required
language: node_js
node_js:
  - '12'
branches:
  only:
    - master
stages:
  - name: hardoor
  - name: test

jobs:
  include:
    - stage: test
      name: "test-1"
      env:
        - GITHUB=https://github.com/SystemLight/hardoor
      script:
        - echo i am test-1

    - stage: test
      name: "test-2"
      env:
        - GITHUB=https://github.com/SystemLight/hardoor
      script:
        - echo i am test-2

    - stage: hardoor
      name: "hardoor-2"
      env:
        - GITHUB=https://github.com/SystemLight/hardoor
      deploy:
        provider: npm
        email: 1466335092@qq.com
        skip_cleanup: true
        tag: latest
        api_key:
          secure: $NPM_TOKEN
        on:
          tags: true
          branch: master
