os: linux
language: node_js
node_js:
  - '10'
branches:
  except:
    - hotfix
stages:
  - name: hardoor
  - name: test
jobs:
  include:
    - stage: test
      name: "test-1"
      env:
        - GITHUB=https://github.com/SystemLight/hardoor
      script:
        - echo i am test-1
    - stage: test
      name: "test-2"
      env:
        - GITHUB=https://github.com/SystemLight/hardoor
      script:
        - echo i am test-2
    - stage: hardoor
      name: "hardoor-1"
      env:
        - GITHUB=https://github.com/SystemLight/hardoor
      before_deploy:
        - echo before_deploy
      deploy:
        provider: npm
        email: 1466335092@qq.com
        skip_cleanup: true
        api_key: "$NPM_TOKEN"
        on:
          tags: true